# Inserts a blank line between shell prompts
add_newline = false

# Force single line
[line_break]
disabled = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[character]

# The "success_symbol" segment is being set to "➜" with the color "bold green"
success_symbol = "[➜](bold green)"
error_symbol = "[✖](bold red)"
vicmd_symbol = "[❮](bold green)"

[directory]
read_only = " "

[git_branch]
symbol = " "
disabled = false

[lua]
disabled = true

[nodejs]
disabled = true

[aws]
disabled = true
symbol = "  "

[conda]
disabled = true
symbol = " "

[dart]
disabled = true
symbol = " "

[docker_context]
disabled = true
symbol = " "

[elixir]
disabled = true
symbol = " "

[elm]
disabled = true
symbol = " "

[golang]
disabled = true
symbol = " "

[hg_branch]
disabled = true
symbol = " "

[java]
disabled = true
symbol = " "

[julia]
disabled = true
symbol = " "

[memory_usage]
disabled = true
symbol = " "

[nim]
disabled = true
symbol = " "

[nix_shell]
disabled = true
symbol = " "

[perl]
disabled = true
symbol = " "

[php]
disabled = true
symbol = " "

[python]
format = '[${symbol}(\($virtualenv\) )]($style)'
disabled = false
symbol = " "

[ruby]
disabled = true
symbol = " "

[rust]
disabled = true
symbol = " "

[scala]
disabled = true
symbol = " "

[shlvl]
disabled = true
symbol = " "

[swift]
disabled = true
symbol = "ﯣ "
