#!/usr/bin/env bash

SOUND="/usr/share/sounds/freedesktop/stereo/audio-volume-change.oga"
UP_ICON="/usr/share/icons/Dracula/24/panel/audio-volume-high.svg"
DOWN_ICON="/usr/share/icons/Dracula/24/panel/audio-volume-low.svg"
MUTED_ICON="/usr/share/icons/Dracula/24/panel/audio-volume-low.svg"

function send_notification() {
	volume=$(pamixer --get-volume)
	dunstify -h int:value:"$volume" -i "$1_ICON" "Volume: ${volume}%" -t 2000 -r 123
}

case $1 in
UP)
	# Set the volume on (if it was muted)
	pamixer -u
	pamixer -i 5 --allow-boost
	send_notification "$1"
	paplay $SOUND
	;;
DOWN)
	pamixer -u
	pamixer -d 5 --allow-boost
	send_notification "$1"
	paplay $SOUND
	;;
MUTE)
	pamixer -t
	if eval pamixer --get-mute; then
		dunstify -i "$MUTED_ICON" -t 2000 "Muted"
	else
		send_notification UP
	fi
	;;
esac
