#!/usr/bin/env bash

#Double layout fr/ara
setxkbmap -model pc105 -layout us_qwerty-fr,ara -option grp:alt_shift_toggle
#Faster cursor
xset r rate 300 50
#Remapping caps lock to super
setxkbmap -option caps:super
#Acts as escape when pressed once
killall xcape 2>/dev/null
xcape -e 'Super_L=Escape'
