#!/usr/bin/env bash

chosen=$(printf "  Power Off\n  Restart\n  Lock" | tofi --prompt-text=)

case "$chosen" in
"  Power Off") poweroff ;;
"  Restart") reboot ;;
"  Lock") swaylock ;;
*) exit 1 ;;
esac
