#!/usr/bin/env bash

chosen=$(printf "  Power Off\n  Restart\n  Lock" | rofi -dmenu -p 'Power menu:')

case "$chosen" in
"  Power Off") poweroff ;;
"  Restart") reboot ;;
"  Lock") suspend ;;
*) exit 1 ;;
esac
