#!/bin/bash

superCopy() {
    "$(xclip -o -sel c)" >> /tmp/tmpclip.log
}

superPaste() {
    echo -n "$(wofi -dmenu -p 'Select:' </tmp/tmpclip.log)" | xclip -sel c
}

usage() {
    cat <<-EOF
		Usage: "$0" <option>

		-c for Super Copy
		-p for Super Pasting // Using wofi -dmenu
	EOF
}

case $1 in
"-c")
    superCopy
    ;;
"-p")
    superPaste
    ;;
*)
    usage
    ;;
esac
