#!/usr/bin/env python

import re
import os
import tempfile
import requests
import webbrowser
from sys import argv
from pathlib import Path


def init():

    # Checking usage
    if len(argv) != 2:
        print(f"Usage: python {argv[0]} query")
        return 1

    # Querying wallhaven.cc
    user_query = argv[1]
    r = requests.get(
        f"https://wallhaven.cc/api/v1/search?q={user_query}&sorting=views&order=desc"
    )
    output = r.json()["data"]

    # Error handling
    if not output:
        print("Error : No images found")
        return 1

    # Clear terminal and prompt user with instructions
    os.system("cls" if os.name == "nt" else "clear")

    display = """
######################################################
##################### Wallsearch #####################
######################################################

Fetching thumbnails from wallhaven.cc, please wait ...

Please delete the thumbnails you don't like.
"""
    print(display)
    return file_proc(output)


# Download and save image
def get_img(url, path):

    r = requests.get(url)
    with open(path, "wb") as f:
        f.write(r.content)


# Checking for a 'Pictures' folder in home directory
def pictures():
    p = f"{Path.home()}{os.path.sep}MEGA{os.path.sep}Images"
    if os.path.exists(p):
        return p
    os.mkdir(p)
    return p


def file_proc(output):

    d = {}

    # Creating temporary folder
    with tempfile.TemporaryDirectory() as tmp:

        # Looping through json output
        for i in range(len(output)):

            # Saving small thumbnail's url
            url = output[i]["thumbs"]["small"]
            # Saving image id
            image_id = output[i]["id"]
            # Saving full hd image's url link
            image_url = output[i]["path"]
            # Getting file extension
            s = re.search(r"\..{3}$", image_url)
            if not s:
                ext = ".jpg"
            else:
                ext = s.group(0)

            d[image_id] = image_url

            # Building full local path to image
            image_path = image_id + ext
            fullpath = tmp + os.path.sep + image_path

            get_img(url, fullpath)

        # Openning tmp folder for user interaction
        webbrowser.open(tmp)
        input("Press Enter key to continue ...")
        print("")

        # For each remaining image in folder
        with os.scandir(tmp) as it:

            # If user deleted every thumbnail
            if not os.listdir(tmp):

                # Display message and exit
                print("Everything was deleted... Terminating now.")
                print("")
                return 0

            print("Downloading FHD images, please wait...")
            print("")

            for entry in it:

                # Get image file name & build full local path
                image_id = os.path.splitext(entry.name)[0]
                fullpath = pictures() + os.path.sep + entry.name

                get_img(d[image_id], fullpath)

    # Openning 'Pictures' folder for final display
    webbrowser.open(pictures())
    print("Enjoy your new wallpapers!")
    return 0


if __name__ == "__main__":
    init()
