#!/usr/bin/env bash

swayidle -w \
    timeout 120 'swaylock' \
    timeout 180 'hyprctl dispatch dpms off' \
    timeout 200 'systemctl suspend' \
    resume 'hyprctl dispatch dpms on' \
    before-sleep 'swaylock'
