require("packer-config")
require("term-config")
require("lsp")
require("dbg")
require("binds")
require("settings")
require("telescope-config")
require("tree-config")
require("xline-config")
require("indent-config")
require("comment-config")
require("colorizer-config")
require("autopairs-config")
require("treesitter-config")
require("themes.catppuccin")
-- require("themes.pywal")
